name: NetBSD Autotools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: '10.0' }
          - { version: '9.3'  }

    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.version}}-autotools
      cancel-in-progress: true

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Startup VM
      uses: cross-platform-actions/action@141cc293701219fd2f72b3abd9ca1fc322cf7d84
      with:
        architecture: x86_64
        hypervisor: qemu
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: runner-to-vm
        shutdown_vm: false
        run: true
    - name: Install dependencies
      uses: cross-platform-actions/action@141cc293701219fd2f72b3abd9ca1fc322cf7d84
      with:
        architecture: x86_64
        hypervisor: qemu
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          sudo pkgin -y install subversion git p5-XML-XPath mawk
          sudo pkgin -y install gmake pkgconf
          sudo pkgin -y install mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio SDL2
          sudo pkgin -y install gcc7-libs   # for libstdc++7
          sudo pkgin -y install autoconf autoconf-archive automake libtool libltdl
          sudo pkgin -y install help2man
          #sudo pkgin -y install doxygen   # broken
    - name: Build
      uses: cross-platform-actions/action@141cc293701219fd2f72b3abd9ca1fc322cf7d84
      with:
        architecture: x86_64
        hypervisor: qemu
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          ./build/autotools/autoconfiscate.sh
    - name: Shutdown VM
      uses: cross-platform-actions/action@141cc293701219fd2f72b3abd9ca1fc322cf7d84
      with:
        architecture: x86_64
        hypervisor: qemu
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: true
        run: true
